### ISSUE TITLE
[FEATURE]1.19 compability

### ISSUE THREAD

**Issue by FriedChickenChina** [SpeedcraftTeam/ThirstPlugin#1]
Hello, this version of the plugin is not compatible with server versions above 1.16, could you please adapt it for newer versions? Much appreciated.

**Comment by Kuba663** [comment]
# Good Morning
I'll work on it now.

**Comment by Kuba663** [comment]
One more question. Did you use paper or spigot?

**Comment by FriedChickenChina** [comment]
I mainly use paper.

**Comment by FriedChickenChina** [comment]
both
